//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int Id_pic { get; set; }
        public string Name { get; set; }
        public int Exhibition_id { get; set; }
        public int Artist_id { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Exhibition Exhibition { get; set; }
    }
}
