//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Exhibitions = new HashSet<Exhibition>();
        }
    
        public int Id_status { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Exhibition> Exhibitions { get; set; }
    }
}
